### ISSUE TITLE
Failed to obtain/convert traceback!

### ISSUE THREAD

**Issue by kaka77** [TunMax/tun2socks_gui_for_windows#1]
Windows 11 系统打开报错，环境py3。

![Snipaste_2022-01-21_10-43-30](https://user-images.githubusercontent.com/8677125/150456502-9a27032c-cbc7-48bf-89ae-1723c2d46267.png)

**Comment by TunMax** [comment]
看报错，是config中Server项中的域名解释为ip地址时出错。用nslookup手动查找这个域名的实际ip地址，在config中Server填入ip，不写域名，应该就可以解决这个问题了。

如果还是想用域名填写，将本机的DNS服务器改为223.5.5.5后再试试。
