### ISSUE TITLE
v2rayn不能配置直连规则，只能走全局代理？

### ISSUE THREAD

**Issue by lenhoo** [TunMax/tun2socks_gui_for_windows#5]
在v2rayn中配置白名单geosite:cn会出现死循环，不配置的话又会让国内网站走代理，这个怎么解决呢？

**Comment by TunMax** [comment]
暂时没有想到好的解决办法。

有以下一个办法可以参考：
在局域网的另一台机器运行v2rayn，然后tun的代理地址对接这个v2rayn的监听端口，这种情况下v2rayn可以设置直连规则。

**Comment by returnL** [comment]
> 暂时没有想到好的解决办法。
> 
> 有以下一个办法可以参考： 在局域网的另一台机器运行v2rayn，然后tun的代理地址对接这个v2rayn的监听端口，这种情况下v2rayn可以设置直连规则。

能否根据进程来分流呢？TunMax不捕获v2rayN和v2ray-Core的流量，这样就不会死循环了
