### ISSUE TITLE
这是什么情况？

### ISSUE THREAD

**Issue by GonewtwLyb** [TunMax/tun2socks_gui_for_windows#6]
![P20516-144855.jpg](https://user-images.githubusercontent.com/89258817/168534987-6333f31b-7c47-46dc-bb0d-c809cc1ef7f3.jpg)

**Comment by brianler** [comment]
dns没有将域名解释成功，试试将你的域名换成ip填写在配置文件上面。

**Comment by TunMax** [comment]
程序已更新到0.1.5版本，可以减少类似的情况发生。
