### ISSUE TITLE
增加对ip段的支持

### ISSUE THREAD

**Issue by jleaves** [TunMax/tun2socks_gui_for_windows#7]
建议在配置文件中增加对ip段的支持，比如 `224.0.0.0/24` `17.0.0.0/8` 这种ip段。

Please support IP ranges for the config.

**Comment by TunMax** [comment]
你好，Netch作者已回归，重新启动维护Netch项目，可转至其项目：https://github.com/netchx/netch

本项目后续可能不再有太大的变化。
