### ISSUE TITLE
IPV6 支持

### ISSUE THREAD

**Issue by arm64v8a** [TunMax/tun2socks_gui_for_windows#9]
目前在 IPV4+IPV6 网络下，虚拟网卡没有 IPV6 路由，由于 V6 优先级比 V4 高，会造成一些网站自动走直连。

建议添加 IPV6 Unreachable 或者实现 IPV6 模式。

**Comment by arm64v8a** [comment]
另外一个问题：通过 Windows API (GetAddrInfo) 查询 DNS 不会走代理，仍然存在 DNS 污染。

即使已经设置 DNS IP (路由器IP) 走 VPN，nslookup 的查询也能确认走了 VPN，但是用的 GetAddrInfo 查询还是走直连，包括浏览器也是用的这个。所以这方面可能需要适配一下。

**Comment by TunMax** [comment]
你好，Netch作者已回归，重新启动维护Netch项目，可转至其项目：https://github.com/netchx/netch

本项目后续可能不再有太大的变化。
